Models/Jugadores.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Lab1_1084120_1070720.Models
{
    public class Jugadores : IComparable
    {
        public int Id { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Required]
        public string Posicion { get; set; }
        [Required]
        public double Salario { get; set; }
        [Required]
        public string Club { get; set; }

        public int CompareTo(object obj)
        {
            var comparer = ((Jugadores)obj).Id;
            return comparer < Id ? 1 : comparer == Id ? 0 : -1;
        }

        public Comparison<Jugadores> SortById = delegate (Jugadores j1, Jugadores j2)
        {
            return j1.Id.CompareTo(j2.Id);
        };
        public Comparison<Jugadores> SortByName = delegate (Jugadores j1, Jugadores j2)
        {
            return j1.Nombre.CompareTo(j2.Nombre);
        };
        public Comparison<Jugadores> SortByApellido = delegate (Jugadores j1, Jugadores j2)
        {
            return j1.Apellido.CompareTo(j2.Apellido);
        };
        public Comparison<Jugadores> SortByPosicion = delegate (Jugadores j1, Jugadores j2)
        {
            return j1.Posicion.CompareTo(j2.Posicion);
        };
        public Comparison<Jugadores> SortBySalarioIgual = delegate (Jugadores j1, Jugadores j2)
        {
            return j1.Salario.CompareTo(j2.Salario);
        };
        public Comparison<Jugadores> SortBySalarioMayor = delegate (Jugadores j1, Jugadores j2)
        {
            int salariobase = j1.Salario.CompareTo(j2.Salario);
            //Es igual o menor
            if (salariobase == 0 || salariobase == -1)
            {
                return -1;
            }
            //Es mayor
            else
            {
                return 0;
            }
        };
        public Comparison<Jugadores> SortBySalarioMenor = delegate (Jugadores j1, Jugadores j2)
        {
            int salariobase = j1.Salario.CompareTo(j2.Salario);
            //Es igual o mayor
            if (salariobase == 0 || salariobase == 1)
            {
                return -1;
            }
            //Es menor
            else
            {
                return 0;
            }
        };
        public Comparison<Jugadores> SortByClub = delegate (Jugadores j1, Jugadores j2)
        {
            return j1.Club.CompareTo(j2.Club);
        };


    }


}

Controllers/JugadoresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Lab1_1084120_1070720.Models;
using System.IO;
using System.Web;
using System.Text;
using BibliotecaDeClases;
using System.Diagnostics;
using Microsoft.Extensions.Hosting;

namespace Lab1_1084120_1070720.Controllers
{
    public class JugadoresController : Controller
    {
        public static ListaArtesanal<Jugadores> ListaArtesanalJugadores = new ListaArtesanal<Jugadores>();
        private static bool ListaCSharp;
        public static Stopwatch tiempos = new Stopwatch();

        public ActionResult ImportarCSV()
        {
            return View();
        }
        public ActionResult SeleccionListaAr()
        {
            System.IO.File.WriteAllText(@"CrearLog.txt", "  OPERACIONES CON TIEMPO \n");
            ListaCSharp = false;
            return View("JugadoresListas");
        }
        public ActionResult SeleccionListaC()
        {
            System.IO.File.WriteAllText(@"CrearLog.txt", "  OPERACIONES CON TIEMPO \n");
            ListaCSharp = true;
            return View("JugadoresListas");
        }

        //POST Importar Archivo
        [HttpPost]
        public IActionResult ImportarCSV(IFormFile ArchivoCSV)
        {
            tiempos.Restart();
            //Lee el archivo
            if (ArchivoCSV.FileName.Contains(".csv"))
            {

                try
                {
                    using (var reader = new StreamReader(ArchivoCSV.OpenReadStream()))
                    {
                        string archivolineas = reader.ReadToEnd().Remove(0, 72); //Elimina Encabezados
                        foreach (string linea in archivolineas.Split("\n"))
                        {
                            if (!string.IsNullOrEmpty(linea))
                            {
                                string[] lineajugador = linea.Split(",");
                                Jugadores Jugador = new Jugadores();
                                Jugador.Club = lineajugador[0];
                                Jugador.Apellido = lineajugador[1];
                                Jugador.Nombre = lineajugador[2];
                                Jugador.Posicion = lineajugador[3];
                                Jugador.Salario = Convert.ToDouble(lineajugador[4]);
                                if (ListaCSharp == true)
                                {
                                    //Agregar a la lista de C#
                                    Jugador.Id = Convert.ToInt32(Singleton.Instance.ListaJugadores.Count);
                                    Singleton.Instance.ListaJugadores.Add(Jugador);
                                }
                                else
                                {
                                    //Agregar a la lista artesanal}
                                    Jugador.Id = ListaArtesanalJugadores.contador;
                                    ListaArtesanalJugadores.AddArtesanal(Jugador);
                                }
                            }
                            else
                            {
                                break;
                            }
                        }
                    }
                    tiempos.Stop();
                    ViewBag.Message = "Operación Finalizada en " + tiempos + " milisegundos";
                    CrearLog("Importar Archivo de CSV, Tiempo empleado en milisegundos " + tiempos + "\n");
                    return RedirectToAction(nameof(Index));

                }
                catch (Exception)
                {
                    //Mensaje de Error
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                return View("ImportarCSV");
            }


        }



        // GET: JugadorController
        public ActionResult Index()
        {
            if (ListaCSharp == true)
            {
                //Mostrar a la lista de C#
                return View(Singleton.Instance.ListaJugadores);
            }
            if (ListaCSharp == false)
            {
                //Mostrar a la lista artesanal
                return View(ListaArtesanalJugadores);
            }
            return View();
        }

        // GET: JugadorController/Details/5
        public ActionResult DetallesJugador(int id)
        {
            var VistaJugador = Singleton.Instance.ListaJugadores.Find(x => x.Id == id);
            return View(VistaJugador);
        }

        // GET: JugadorController/Create
        public ActionResult CrearJugador()
        {
            return View();
        }

        // POST: JugadorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearJugador(IFormCollection collection)
        {
            try
            {
                tiempos.Restart();
                var nuevoJugador = new Models.Jugadores
                {

                    Nombre = collection["Nombre"],
                    Apellido = collection["Apellido"],
                    Posicion = collection["Posicion"],
                    Salario = Convert.ToDouble(collection["Salario"]),
                    Club = collection["Club"]
                };
                if (ListaCSharp == true)
                {
                    //Crear a la lista de C#
                    nuevoJugador.Id = Convert.ToInt32(Singleton.Instance.ListaJugadores.Count);
                    Singleton.Instance.ListaJugadores.Add(nuevoJugador);
                }
                else
                {
                    //Crear a la lista artesanal
                    nuevoJugador.Id = ListaArtesanalJugadores.contador;
                    ListaArtesanalJugadores.AddArtesanal(nuevoJugador);
                }
                tiempos.Stop();
                ViewBag.Message = "Operación Finalizada en " + tiempos + " milisegundos";
                CrearLog("Crear Jugador, Tiempo empleado en milisegundos " + tiempos + '\n');
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: JugadorController/Edit/5
        public ActionResult EditarJugador(int id)
        {

            Jugadores editarJugador = new Jugadores();
            editarJugador.Id = id;
            if (ListaCSharp == true)
            {
                //Busca en la lista de C#
                editarJugador = Singleton.Instance.ListaJugadores.Find(x => x.Id == id);
            }
            else
            {
                //Busca en la lista artesanal
                editarJugador = ListaArtesanalJugadores.BuscarIdArtesanal(editarJugador.SortById, editarJugador);
            }

            return View(editarJugador);
        }

        // POST: JugadorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarJugador(int id, IFormCollection collection)
        {
            try
            {
                tiempos.Restart();
                Jugadores editarJugador = new Jugadores();
                editarJugador.Id = id;
                editarJugador.Nombre = collection["Nombre"];
                editarJugador.Apellido = collection["Apellido"];
                editarJugador.Posicion = collection["Posicion"];
                editarJugador.Salario = Convert.ToDouble(collection["Salario"]);
                editarJugador.Club = collection["Club"];
                if (ListaCSharp == true)
                {
                    //Edita a la lista de C#
                    Singleton.Instance.ListaJugadores.Find(x => x.Id == id).Salario = Convert.ToDouble(collection["Salario"]);
                    Singleton.Instance.ListaJugadores.Find(x => x.Id == id).Club = collection["Club"];

                }
                else
                {
                    //Edita a la lista artesanal
                    ListaArtesanalJugadores.Editar(editarJugador.SortById, editarJugador);
                }
                tiempos.Stop();
                ViewBag.Message = "Operación Finalizada en " + tiempos + " milisegundos";
                CrearLog("Editar Jugador, Tiempo empleado en milisegundos " + tiempos + '\n');
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: JugadorController/Delete/5
        public ActionResult EliminarJugador(int id)
        {
            tiempos.Restart();
            Jugadores eliminarJugador = new Jugadores();
            eliminarJugador.Id = id;
            if (ListaCSharp == true)
            {
                //Elimina en la lista de C#
                eliminarJugador = Singleton.Instance.ListaJugadores.Find(x => x.Id == id);
            }
            else
            {
                //Elimina en la lista artesanal
                eliminarJugador = ListaArtesanalJugadores.BuscarIdArtesanal(eliminarJugador.SortById, eliminarJugador);
            }
            tiempos.Stop();
            ViewBag.Message = "Operación Finalizada en " + tiempos + " milisegundos";
            CrearLog("Eliminar Jugador, Tiempo empleado en milisegundos " + tiempos + '\n');
            return View(eliminarJugador);
            if (eliminarJugador == null)
            {
                return NotFound();
            }
        }

        // POST: JugadorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EliminarJugador(int id, IFormCollection collection)
        {
            try
            {
                tiempos.Restart();
                Jugadores eliminarJugador = new Jugadores();
                eliminarJugador.Id = id;

Views/Jugadores/Busquedas.cshtml
@model IEnumerable<Lab1_1084120_1070720.Models.Jugadores>

@{
    ViewData["Title"] = "Busquedas";
}

<h1>Buscar Jugadores</h1>


<form asp-controller="Jugadores" asp-action="Busquedas">
    <div class="radio">
        <label>
            <input type="radio" name="Filtros" id="Filtros" value="Nombre"> Nombre
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="Filtros" id="Filtros" value="Apellido">Apellido
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="Filtros" id="Filtros" value="Posicion">Posicion
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="Filtros" id="Filtros" value="SalarioMayor"> Salario Mayor
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="Filtros" id="Filtros" value="SalarioMenor">Salario Menor
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="Filtros" id="Filtros" value="SalarioIgual">Salario Igual
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" name="Filtros" id="Filtros" value="Club">Club
        </label>
    </div>
    <input class="form-control" type="search" value="" placeholder="Search" aria-label="Search" name="TextoBusqueda">
    <button class="btn btn-outline-info" role="button" type="submit">Buscar</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Posicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Club)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Posicion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Club)
                </td>
                <td>
                    @Html.ActionLink("Editar Jugador", "EditarJugador", new { id = item.Id }) |
                    @Html.ActionLink("Detalles Jugador", "DetallesJugador", new { id = item.Id }) |
                    @Html.ActionLink("Eliminar Jugador", "EliminarJugador", new { id = item.Id })
                </td>
            </tr>
        }

        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("Tiempo de ejecución " + tiempos + " milisegundos";
                };
            </script>
        }
    </tbody>
</table>

Views/Jugadores/CrearJugador.cshtml
@model Lab1_1084120_1070720.Models.Jugadores

@{
    ViewData["Title"] = "CrearJugador";
}

<h1>Crear Jugador</h1>

<h4>Jugador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CrearJugador">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Posicion" class="control-label"></label>
                <input asp-for="Posicion" class="form-control" />
                <span asp-validation-for="Posicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Club" class="control-label"></label>
                <input asp-for="Club" class="form-control" />
                <span asp-validation-for="Club" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("Tiempo de ejecución " + tiempos + " milisegundos";
        };
    </script>
}

<div>
    <a asp-action="Index">Regresar a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Jugadores/DetallesJugador.cshtml
@model Lab1_1084120_1070720.Models.Jugadores

@{
    ViewData["Title"] = "Detalles Jugadores";
}

<h1>Detalles Jugador</h1>

<div>
    <h4>Jugador</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Posicion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Posicion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Club)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Club)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Regresar a Lista</a>
</div>

Views/Jugadores/EditarJugador.cshtml
@model Lab1_1084120_1070720.Models.Jugadores

@{
    ViewData["Title"] = "EditarJugador";
}

<h1>Editar Jugador</h1>

<h4>Jugador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarJugador">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" readonly />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" readonly />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Posicion" class="control-label"></label>
                <input asp-for="Posicion" class="form-control" readonly />
                <span asp-validation-for="Posicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Club" class="control-label"></label>
                <input asp-for="Club" class="form-control" />
                <span asp-validation-for="Club" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@if (ViewBag.Message != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("Tiempo de ejecución " + tiempos + " milisegundos";
        };
    </script>
}

<div>
    <a asp-action="Index">Regresar a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Jugadores/EliminarJugador.cshtml
@model Lab1_1084120_1070720.Models.Jugadores

@{
    ViewData["Title"] = "EliminarJugador";
}

<h1>Eliminar Jugador</h1>

<h3>¿Está seguro que quiere eliminar a este jugador?</h3>
<div>
    <h4>Jugador</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Posicion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Posicion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Club)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Club)
        </dd>
    </dl>
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("Tiempo de ejecución " + tiempos + " milisegundos";
            };
        </script>
    }
    <form asp-action="EliminarJugador">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar a la Lista</a>
    </form>
</div>

Views/Jugadores/ImportarCSV.cshtml
@model IEnumerable<Lab1_1084120_1070720.Models.Jugadores>

@{
    ViewData["Title"] = "ImportarCSV";
}

<h1>Importar Archivo</h1>

<h4> Subir Archivo</h4>

<form method="post" enctype="multipart/form-data" asp-controller="Jugadores" asp-action="ImportarCSV">
    <input type="file" name="ArchivoCSV" />
    <p>



    </p>
    <button type="submit">Subir archivo CSV</button>

    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("Tiempo de ejecución " + tiempos + " milisegundos";
            };
        </script>
    }
</form>

Views/Jugadores/Index.cshtml
@model IEnumerable<Lab1_1084120_1070720.Models.Jugadores>

@{
    ViewData["Title"] = "Index";
}

<h1>Listado de Jugadores</h1>


<a asp-action="CrearJugador" class="btn btn-outline-info " role="button">Crear Nuevo Jugador</a>


<a asp-action="Busquedas" class="btn btn-outline-info " role="button">Buscar Jugadores</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Posicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Club)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Posicion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Club)
                </td>
                <td>
                    @Html.ActionLink("Editar Jugador", "EditarJugador", new { id = item.Id }) |
                    @Html.ActionLink("Detalles Jugador", "DetallesJugador", new { id = item.Id }) |
                    @Html.ActionLink("Eliminar Jugador", "EliminarJugador", new { id = item.Id })
                </td>
            </tr>
        }
        @if (ViewBag.Message != null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    alert("Tiempo de ejecución " + tiempos + " milisegundos";
                };
            </script>
        }
    </tbody>
</table>

Views/Jugadores/JugadoresListas.cshtml
@{
    ViewData["Title"] = "Agregar Jugadores a la Lista";
}

<div class="text-center">
    <p>

    </p>
    <p>

    </p>
    <h1 class="display-4">Agregue los Jugadores a la Lista Seleccionada</h1>

    <div class="btn-group" role="group">
        <a asp-controller="Jugadores" asp-action="CrearJugador"
           class="btn btn-primary">
            Agregar Manualmente
        </a>
    </div>



    <div class="btn-group" role="group">
        <a asp-controller="Jugadores" asp-action="ImportarCSV"
           class="btn btn-primary">
            Importar Archivo CSV
        </a>
    </div>
    @if (ViewBag.Message != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("Tiempo de ejecución " + tiempos + " milisegundos";
            };
        </script>
    }


</div>